version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src  # монтируем код для hot-reload
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - app
    volumes:
      - ./src:/app/src
    command: celery -A src.tasks.worker worker --loglevel=info

  flower:
    build: .
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    command: celery -A src.tasks.worker flower --port=5555

volumes:
  postgres_data: